# Assessment

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [25]:
df = pd.read_csv("Comcast_telecom_complaints_data.csv")

In [26]:
df

,Ticket #,Customer Complaint,Date,Date_month_year,Time,Received Via,City,State,Zip code,Status,Filing on Behalf of Someone
0,250635,Comcast Cable Internet Speeds,22-04-15,22-Apr-15,3:53:50 PM,Customer Care Call,Abingdon,Maryland,21009,Closed,No
1,223441,Payment disappear - service got disconnected,4/8/2015,4-Aug-15,10:22:56 AM,Internet,Acworth,Georgia,30102,Closed,No
2,242732,Speed and Service,18-04-15,18-Apr-15,9:55:47 AM,Internet,Acworth,Georgia,30101,Closed,Yes
3,277946,Comcast Imposed a New Usage Cap of 300GB that ...,5/7/2015,5-Jul-15,11:59:35 AM,Internet,Acworth,Georgia,30101,Open,Yes
4,307175,Comcast not working and no service to boot,26-05-15,26-May-15,1:25:26 PM,Internet,Acworth,Georgia,30101,Solved,No
...,...,...,...,...,...,...,...,...,...,...,...
2219,213550,Service Availability,4/2/2015,4-Feb-15,9:13:18 AM,Customer Care Call,Youngstown,Florida,32466,Closed,No
2220,318775,Comcast Monthly Billing for Returned Modem,6/2/2015,6-Feb-15,1:24:39 PM,Customer Care Call,Ypsilanti,Michigan,48197,Solved,No
2221,331188,complaint about comcast,6/9/2015,6-Sep-15,5:28:41 PM,Internet,Ypsilanti,Michigan,48197,Solved,No
2222,360489,Extremely unsatisfied Comcast customer,23-06-15,23-Jun-15,11:13:30 PM,Customer Care Call,Ypsilanti,Michigan,48197,Solved,No
2223,363614,"Comcast, Ypsilanti MI Internet Speed",24-06-15,24-Jun-15,10:28:33 PM,Customer Care Call,Ypsilanti,Michigan,48198,Open,Yes

In [27]:
results = df.groupby("Status")

In [28]:
results

In [29]:
results.groups

{'Closed': [0, 1, 2, 8, 10, 11, 17, 18, 19, 27, 30, 36, 43, 44, 45, 46, 55, 56, 57, 58, 66, 67, 69, 71, 72, 73, 74, 75, 76, 77, 78, 81, 97, 98, 99, 130, 139, 141, 153, 158, 162, 164, 166, 168, 181, 184, 186, 193, 199, 201, 202, 203, 206, 207, 210, 211, 212, 215, 218, 220, 224, 230, 234, 239, 240, 241, 242, 243, 251, 254, 260, 261, 262, 266, 267, 268, 269, 271, 275, 284, 287, 288, 290, 291, 298, 300, 306, 308, 313, 314, 316, 320, 321, 322, 333, 340, 341, 344, 346, 349, ...], 'Open': [3, 9, 12, 23, 25, 26, 38, 39, 40, 41, 61, 65, 82, 84, 88, 89, 90, 96, 106, 112, 118, 125, 127, 131, 136, 137, 140, 150, 152, 155, 157, 165, 167, 169, 176, 185, 189, 190, 192, 195, 208, 219, 227, 228, 232, 233, 244, 245, 248, 249, 250, 253, 264, 270, 276, 279, 286, 303, 317, 324, 328, 332, 348, 359, 371, 401, 406, 429, 432, 442, 445, 450, 454, 459, 463, 489, 490, 492, 499, 513, 514, 520, 532, 548, 550, 560, 577, 579, 580, 581, 583, 590, 592, 595, 601, 602, 606, 618, 619, 622, ...], 'Pending': [6, 15, 29, 114, 115, 116, 117, 121, 128, 129, 132, 138, 151, 154, 156, 160, 175, 183, 191, 196, 216, 229, 265, 301, 304, 310, 357, 361, 366, 372, 382, 479, 485, 495, 496, 500, 504, 519, 524, 525, 537, 543, 575, 578, 600, 603, 616, 623, 632, 634, 646, 653, 677, 687, 693, 696, 699, 701, 714, 720, 726, 745, 761, 768, 800, 819, 824, 863, 874, 879, 888, 894, 943, 947, 1024, 1025, 1029, 1033, 1039, 1057, 1058, 1074, 1075, 1096, 1106, 1122, 1136, 1137, 1145, 1148, 1166, 1194, 1254, 1281, 1282, 1329, 1350, 1351, 1385, 1399, ...], 'Solved': [4, 5, 7, 13, 14, 16, 20, 21, 22, 24, 28, 31, 32, 33, 34, 35, 37, 42, 47, 48, 49, 50, 51, 52, 53, 54, 59, 60, 62, 63, 64, 68, 70, 79, 80, 83, 85, 86, 87, 91, 92, 93, 94, 95, 100, 101, 102, 103, 104, 105, 107, 108, 109, 110, 111, 113, 119, 120, 122, 123, 124, 126, 133, 134, 135, 142, 143, 144, 145, 146, 147, 148, 149, 159, 161, 163, 170, 171, 172, 173, 174, 177, 178, 179, 180, 182, 187, 188, 194, 197, 198, 200, 204, 205, 209, 213, 214, 217, 221, 222, ...]}

In [30]:
results.groups.keys()

dict_keys(['Closed', 'Open', 'Pending', 'Solved'])

In [85]:
for group, df in results:
    total_Closed = len(df[df["Status"]=="Closed"])
    total_Open = len(df[df["Status"]=="Open"])
    total_Pending = len(df[df["Status"]=="Pending"])
    total_Solved = len(df[df["Status"]=="Solved"])
    print("Closed:{}\nOpen:{}\nPending:{}\nSolved:{}".format(total_Closed, total_Open, total_Pending, total_Solved))

Closed:734
Open:0
Pending:0
Solved:0
Closed:0
Open:363
Pending:0
Solved:0
Closed:0
Open:0
Pending:154
Solved:0
Closed:0
Open:0
Pending:0
Solved:973

In [31]:
names=[]
case=[]
for Status, df2 in results:
    print("{}:{}".format(Status,len(df2)))
    names.append(Status)
    case.append(len(df2))

Closed:734
Open:363
Pending:154
Solved:973

In [32]:
highest_case_state = df.groupby("State")

In [33]:
highest_case_state.groups.keys()

dict_keys(['Alabama', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District Of Columbia', 'District of Columbia', 'Florida', 'Georgia', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'Ohio', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia'])

In [34]:
l_states = []
l_cases = []
for Status, df3 in highest_case_state:
    print("{}:{}".format(Status,len(df3)))
    #df["Case_count"] = len(df) 
    l_states.append(Status)
    l_cases.append(len(df3))

Alabama:26
Arizona:20
Arkansas:6
California:220
Colorado:80
Connecticut:12
Delaware:12
District Of Columbia:16
District of Columbia:1
Florida:240
Georgia:288
Illinois:164
Indiana:59
Iowa:1
Kansas:2
Kentucky:7
Louisiana:13
Maine:5
Maryland:78
Massachusetts:61
Michigan:115
Minnesota:33
Mississippi:39
Missouri:4
Montana:1
Nevada:1
New Hampshire:12
New Jersey:75
New Mexico:15
New York:6
North Carolina:3
Ohio:3
Oregon:49
Pennsylvania:130
Rhode Island:1
South Carolina:18
Tennessee:143
Texas:71
Utah:22
Vermont:3
Virginia:60
Washington:98
West Virginia:11

In [35]:
df

,Ticket #,Customer Complaint,Date,Date_month_year,Time,Received Via,City,State,Zip code,Status,Filing on Behalf of Someone
0,250635,Comcast Cable Internet Speeds,22-04-15,22-Apr-15,3:53:50 PM,Customer Care Call,Abingdon,Maryland,21009,Closed,No
1,223441,Payment disappear - service got disconnected,4/8/2015,4-Aug-15,10:22:56 AM,Internet,Acworth,Georgia,30102,Closed,No
2,242732,Speed and Service,18-04-15,18-Apr-15,9:55:47 AM,Internet,Acworth,Georgia,30101,Closed,Yes
3,277946,Comcast Imposed a New Usage Cap of 300GB that ...,5/7/2015,5-Jul-15,11:59:35 AM,Internet,Acworth,Georgia,30101,Open,Yes
4,307175,Comcast not working and no service to boot,26-05-15,26-May-15,1:25:26 PM,Internet,Acworth,Georgia,30101,Solved,No
...,...,...,...,...,...,...,...,...,...,...,...
2219,213550,Service Availability,4/2/2015,4-Feb-15,9:13:18 AM,Customer Care Call,Youngstown,Florida,32466,Closed,No
2220,318775,Comcast Monthly Billing for Returned Modem,6/2/2015,6-Feb-15,1:24:39 PM,Customer Care Call,Ypsilanti,Michigan,48197,Solved,No
2221,331188,complaint about comcast,6/9/2015,6-Sep-15,5:28:41 PM,Internet,Ypsilanti,Michigan,48197,Solved,No
2222,360489,Extremely unsatisfied Comcast customer,23-06-15,23-Jun-15,11:13:30 PM,Customer Care Call,Ypsilanti,Michigan,48197,Solved,No
2223,363614,"Comcast, Ypsilanti MI Internet Speed",24-06-15,24-Jun-15,10:28:33 PM,Customer Care Call,Ypsilanti,Michigan,48198,Open,Yes

In [36]:
new_df = pd.DataFrame(
    {
        "State" : l_states,
        "Cases" : l_cases
    }
)

In [37]:
new_df.sort_values(by='Cases', ascending=False)

                   State  Cases
10               Georgia    288
9                Florida    240
3             California    220
11              Illinois    164
36             Tennessee    143
33          Pennsylvania    130
20              Michigan    115
41            Washington     98
4               Colorado     80
18              Maryland     78
27            New Jersey     75
37                 Texas     71
19         Massachusetts     61
40              Virginia     60
12               Indiana     59
32                Oregon     49
22           Mississippi     39
21             Minnesota     33
0                Alabama     26
38                  Utah     22
1                Arizona     20
35        South Carolina     18
7   District Of Columbia     16
28            New Mexico     15
16             Louisiana     13
5            Connecticut     12
26         New Hampshire     12
6               Delaware     12
42         West Virginia     11
15              Kentucky      7
2               Arkansas      6
29              New York      6
17                 Maine      5
23              Missouri      4
30        North Carolina      3
39               Vermont      3
31                  Ohio      3
14                Kansas      2
8   District of Columbia      1
34          Rhode Island      1
13                  Iowa      1
25                Nevada      1
24               Montana      1

In [38]:
df

,Ticket #,Customer Complaint,Date,Date_month_year,Time,Received Via,City,State,Zip code,Status,Filing on Behalf of Someone
0,250635,Comcast Cable Internet Speeds,22-04-15,22-Apr-15,3:53:50 PM,Customer Care Call,Abingdon,Maryland,21009,Closed,No
1,223441,Payment disappear - service got disconnected,4/8/2015,4-Aug-15,10:22:56 AM,Internet,Acworth,Georgia,30102,Closed,No
2,242732,Speed and Service,18-04-15,18-Apr-15,9:55:47 AM,Internet,Acworth,Georgia,30101,Closed,Yes
3,277946,Comcast Imposed a New Usage Cap of 300GB that ...,5/7/2015,5-Jul-15,11:59:35 AM,Internet,Acworth,Georgia,30101,Open,Yes
4,307175,Comcast not working and no service to boot,26-05-15,26-May-15,1:25:26 PM,Internet,Acworth,Georgia,30101,Solved,No
...,...,...,...,...,...,...,...,...,...,...,...
2219,213550,Service Availability,4/2/2015,4-Feb-15,9:13:18 AM,Customer Care Call,Youngstown,Florida,32466,Closed,No
2220,318775,Comcast Monthly Billing for Returned Modem,6/2/2015,6-Feb-15,1:24:39 PM,Customer Care Call,Ypsilanti,Michigan,48197,Solved,No
2221,331188,complaint about comcast,6/9/2015,6-Sep-15,5:28:41 PM,Internet,Ypsilanti,Michigan,48197,Solved,No
2222,360489,Extremely unsatisfied Comcast customer,23-06-15,23-Jun-15,11:13:30 PM,Customer Care Call,Ypsilanti,Michigan,48197,Solved,No
2223,363614,"Comcast, Ypsilanti MI Internet Speed",24-06-15,24-Jun-15,10:28:33 PM,Customer Care Call,Ypsilanti,Michigan,48198,Open,Yes

In [95]:
'''
for Status, df in highest_case_state:
    df.sort_values(by='len(df)', ascending=False)
'''

"\nfor Status, df in highest_case_state:\n    df.sort_values(by='len(df)', ascending=False)\n"

In [39]:
l_states = []
l_cases_open = []
l_cases_closed = []
l_cases_pending = []
l_cases_solved = []
for State, df2 in highest_case_state:
    #print("{}:{}".format(Status,len(df))) 
    print(df2["Status"])
    l_states.append(State)
    l_cases_open.append(len(df2[df2["Status"]=="Open"]))
    l_cases_closed.append(len(df2[df2["Status"]=="Closed"]))
    l_cases_pending.append(len(df2[df2["Status"]=="Pending"]))
    l_cases_solved.append(len(df2[df2["Status"]=="Solved"]))
    #print(l_cases_closed)

135      Solved
492        Open
598      Closed
693     Pending
744      Solved
745     Pending
761     Pending
800     Pending
908      Closed
909      Solved
910      Solved
911      Solved
912      Solved
913        Open
1189       Open
1190     Solved
1308     Closed
1309     Closed
1360       Open
1438     Closed
1490     Closed
2040     Solved
2048     Closed
2079     Solved
2080    Pending
2081     Closed
Name: Status, dtype: object
1487     Solved
2057     Closed
2058     Closed
2059     Closed
2060     Closed
2061     Solved
2062       Open
2063     Closed
2064     Solved
2065     Solved
2066     Solved
2067       Open
2068     Closed
2069     Solved
2070     Solved
2071    Pending
2072    Pending
2073    Pending
2074     Solved
2075    Pending
Name: Status, dtype: object
949     Solved
1151    Closed
1152    Solved
1153    Solved
1154    Solved
1431    Solved
Name: Status, dtype: object
8        Closed
9          Open
43       Closed
44       Closed
53       Solved
         ...
2088     Closed
2089     Solved
2108    Pending
2109     Solved
2188     Solved
Name: Status, Length: 220, dtype: object
68       Solved
147      Solved
148      Solved
149      Solved
156     Pending
         ...
1891     Closed
1976     Solved
2043     Closed
2169     Solved
2189     Solved
Name: Status, Length: 80, dtype: object
274      Solved
289      Solved
1191     Solved
1223       Open
1286     Closed
1401       Open
1406     Closed
1407     Solved
1886    Pending
2137     Solved
2138     Solved
2155     Closed
Name: Status, dtype: object
601        Open
1288       Open
1289     Solved
1299       Open
1412     Solved
1863     Solved
1906     Solved
2180     Closed
2181     Closed
2182     Solved
2183     Solved
2184    Pending
Name: Status, dtype: object
2116     Closed
2117     Closed
2118     Closed
2119     Closed
2120     Solved
2121    Pending
2123     Closed
2124     Solved
2125     Solved
2126     Solved
2127     Solved
2128     Solved
2129     Solved
2130     Solved
2131       Open
2135     Solved
Name: Status, dtype: object
2122    Solved
Name: Status, dtype: object
134     Solved
240     Closed
241     Closed
242     Closed
243     Closed
         ...
2163    Solved
2164    Closed
2165    Solved
2172    Closed
2219    Closed
Name: Status, Length: 240, dtype: object
1        Closed
2        Closed
3          Open
4        Solved
5        Solved
         ...
2204     Solved
2205     Solved
2206     Solved
2207     Solved
2208    Pending
Name: Status, Length: 288, dtype: object
25         Open
66       Closed
67       Closed
150        Open
151     Pending
         ...
2176     Solved
2190     Closed
2199     Closed
2209     Solved
2218       Open
Name: Status, Length: 164, dtype: object
16       Solved
136        Open
183     Pending
197      Solved
234      Closed
235      Solved
236      Solved
472      Closed
473      Solved
498      Solved
620      Closed
629      Solved
647        Open
648      Solved
715      Solved
754      Solved
780      Solved
782      Closed
783      Solved
787      Closed
843      Solved
917      Closed
918      Closed
919      Closed
920      Closed
921      Closed
922      Solved
923        Open
924      Solved
925      Solved
926      Solved
927      Closed
928        Open
929      Solved
930      Solved
931      Solved
932      Solved
933        Open
934      Solved
935      Solved
936      Solved
937      Solved
1081     Solved
1082     Solved
1087     Solved
1159       Open
1235       Open
1409     Closed
1419     Solved
1489     Solved
1668     Closed
1890     Solved
1922     Closed
1923     Solved
1924     Solved
2090     Solved
2115     Solved
2156     Closed
2157       Open
Name: Status, dtype: object
2142    Solved
Name: Status, dtype: object
1466     Closed
1467    Pending
Name: Status, dtype: object
363      Solved
646     Pending
697      Solved
1497     Closed
1498     Solved
1499    Pending
1650    Pending
Name: Status, dtype: object
1259     Solved
1316     Closed
1317     Solved
1318     Solved
1893     Closed
1894     Closed
1895     Solved
1896     Closed
1897     Solved
2158     Solved
2159     Solved
2160     Closed
2161    Pending
Name: Status, dtype: object
189       Open
308     Closed
1041    Solved
1925    Solved
2049      Open
Name: Status, dtype: object
0       Closed
50      Solved
164     Closed
165       Open
166     Closed
         ...
2017    Solved
2018    Solved
2019    Solved
2170      Open
2193    Solved
Name: Status, Length: 78, dtype: object
27      Closed
40        Open
157       Open
251     Closed
252     Solved
         ...
2111    Closed
2140    Closed
2168      Open
2185    Solved
2192    Solved
Name: Status, Length: 61, dtype: object
7       Solved
45      Closed
46      Closed
47      Solved
48      Solved
         ...
2212    Closed
2220    Solved
2221    Solved
2222    Solved
2223      Open
Name: Status, Length: 115, dtype: object
42       Solved
52       Solved
237      Solved
238      Solved
314      Closed
315      Solved
375      Closed
491      Solved
633      Closed
635        Open
861      Solved
939      Closed
940      Solved
1302     Solved
1303     Solved
1304     Closed
1331     Solved
1590     Solved
1591     Solved
1592     Solved
1593     Solved
1594     Solved
1667     Solved
1735     Solved
1737       Open
1892     Closed
1970    Pending
1972     Closed
1973     Closed
1974     Solved
1975     Closed
1985    Pending
2166     Solved
Name: Status, dtype: object
271      Closed
272      Solved
273      Solved
343      Solved
815      Closed
816      Closed
817        Open
818      Solved
829      Solved
830        Open
845      Solved
862      Solved
863     Pending
945      Solved
946      Solved
947     Pending
948        Open
1117     Closed
1118     Solved
1192     Solved
1258       Open
1469     Closed
1470       Open
1471     Solved
1472     Solved
1473    Pending
1522    Pending
1523    Pending
1531     Solved
1532    Pending
1682     Closed
1883     Closed
1884       Open
1934       Open
1935       Open
1936       Open
1937     Closed
1938     Solved
2077    Pending
Name: Status, dtype: object
208       Open
916     Closed
1085    Solved
1230    Closed
Name: Status, dtype: object
269    Closed
Name: Status, dtype: object
1112    Closed
Name: Status, dtype: object
41         Open
477      Closed
602        Open
603     Pending
655        Open
801      Closed
1125     Solved
1198     Closed
1199     Solved
1257     Solved
1739     Closed
2187     Solved
Name: Status, dtype: object
184      Closed
191     Pending
192        Open
223      Solved
224      Closed
         ...
2107     Solved
2150     Closed
2154     Solved
2178     Closed
2210     Closed
Name: Status, Length: 75, dtype: object
10       Closed
11       Closed
12         Open
13       Solved
14       Solved
15      Pending
1110     Closed
1111     Solved
1172       Open
1828     Closed
1829     Solved
1830       Open
1831     Solved
1832     Solved
1898     Closed
Name: Status, dtype: object
163     Solved
733     Closed
1260    Solved
1601    Solved
1645    Closed
1915    Solved
Name: Status, dtype: object
1651    Closed
1866    Solved
1953    Closed
Name: Status, dtype: object
471     Closed
630     Solved
2112    Closed
Name: Status, dtype: object
28       Solved
29      Pending
195        Open
196     Pending
347      Solved
487      Closed
488      Solved
489        Open
490        Open
659      Closed
660      Solved
661      Closed
662      Solved
663      Solved
664      Solved
665      Solved
694      Solved
785        Open
806      Closed
807        Open
808      Closed
836      Solved
1014       Open
1086     Solved
1127       Open
1301     Solved
1613     Closed
1614     Closed
1615     Closed
1616     Solved
1617       Open
1618     Solved
1619       Open
1620     Solved
1621     Solved
1622     Solved
1623     Solved
1624     Solved
1625     Solved
1626     Solved
1627     Solved
1628     Solved
1740     Solved
1851     Solved
1963     Solved
1964    Pending
2046     Closed
2054     Solved
2055       Open
Name: Status, dtype: object
26        Open
38        Open
39        Open
51      Solved
139     Closed
         ...
2213    Closed
2214    Solved
2215    Solved
2216    Solved
2217    Closed
Name: Status, Length: 130, dtype: object
1719    Closed
Name: Status, dtype: object
367      Closed
368      Closed
369      Solved
370      Closed
371        Open
372     Pending
373      Solved
769      Solved
770      Solved
994      Solved
1340     Closed
1341     Solved
1342     Solved
1348     Closed
1423     Closed
1424       Open
2003     Solved
2110     Closed
Name: Status, dtype: object
54      Solved
70      Solved
186     Closed
187     Solved
277     Solved
         ...
1697    Solved
1908    Closed
1909      Open
1910    Solved
2177      Open
Name: Status, Length: 143, dtype: object
37      Solved
155       Open
517     Closed
538     Solved
753     Solved
         ...
1999      Open
2000    Solved
2041    Closed
2042      Open
2047    Solved
Name: Status, Length: 71, dtype: object
493     Solved
846       Open
1164    Solved
1203    Closed
1359      Open
1745    Closed
1746    Closed
1747    Closed
1748    Closed
1749      Open
1750    Solved
1751    Solved
1752    Solved
1753    Solved
1809      Open
1903    Closed
1904      Open
1905    Solved
2037    Closed
2038    Solved
2136      Open
2167    Solved
Name: Status, dtype: object
312     Solved
1300    Solved
1734      Open
Name: Status, dtype: object
17       Closed
18       Closed
19       Closed
20       Solved
21       Solved
22       Solved
23         Open
24       Solved
56       Closed
57       Closed
58       Closed
59       Solved
60       Solved
61         Open
62       Solved
63       Solved
64       Solved
65         Open
69       Closed
222      Solved
291      Closed
292      Solved
374      Solved
381      Closed
382     Pending
383      Closed
384      Closed
453      Closed
457      Solved
501      Solved
696     Pending
705      Closed
728      Solved
738      Solved
825      Closed
1161     Closed
1162     Solved
1181     Solved
1197     Solved
1426     Closed
1479     Solved
1641     Solved
1661     Solved
1663       Open
1664     Solved
1670     Solved
1671       Open
1672       Open
1673     Solved
1674    Pending
1675     Solved
1676       Open
1677     Solved
1977     Solved
1980     Closed
2052     Closed
2191     Closed
2194     Closed
2195     Closed
2196       Open
Name: Status, dtype: object
140        Open
141      Closed
142      Solved
159      Solved
160     Pending
         ...
2097       Open
2098     Solved
2099       Open
2197     Solved
2198     Solved

Name: Status, Length: 98, dtype: object
219       Open
313     Closed
680     Closed
906     Closed
907       Open
1228    Closed
1229    Solved
1326      Open
1327    Solved
1655    Closed
2145    Closed
Name: Status, dtype: object

In [40]:
new_df2 = pd.DataFrame(
    {
        "State" : l_states,
        "Open" : l_cases_open,
        "Closed" : l_cases_closed,
        "Pending" : l_cases_pending,
        "Solved" : l_cases_solved
    }
)

In [41]:
new_df2

                   State  Open  Closed  Pending  Solved
0                Alabama     4       8        5       9
1                Arizona     2       6        4       8
2               Arkansas     0       1        0       5
3             California    47      72       14      87
4               Colorado    12      23       10      35
5            Connecticut     2       3        1       6
6               Delaware     3       2        1       6
7   District Of Columbia     1       5        1       9
8   District of Columbia     0       0        0       1
9                Florida    35     100        4     101
10               Georgia    35      82       45     126
11              Illinois    23      57        6      78
12               Indiana     8      15        1      35
13                  Iowa     0       0        0       1
14                Kansas     0       1        1       0
15              Kentucky     0       1        3       3
16             Louisiana     0       5        1       7
17                 Maine     2       1        0       2
18              Maryland    13      24        2      39
19         Massachusetts    10      24        1      26
20              Michigan    18      45        5      47
21             Minnesota     2       9        2      20
22           Mississippi     9       8        7      15
23              Missouri     1       2        0       1
24               Montana     0       1        0       0
25                Nevada     0       1        0       0
26         New Hampshire     3       4        1       4
27            New Jersey    17      23        2      33
28            New Mexico     3       5        1       6
29              New York     0       2        0       4
30        North Carolina     0       2        0       1
31                  Ohio     0       2        0       1
32                Oregon    10       9        3      27
33          Pennsylvania    14      55        6      55
34          Rhode Island     0       1        0       0
35        South Carolina     2       7        1       8
36             Tennessee    33      39       14      57
37                 Texas    18      20        4      29
38                  Utah     6       7        0       9
39               Vermont     1       0        0       2
40              Virginia     8      21        3      28
41            Washington    18      35        5      40
42         West Virginia     3       6        0       2

In [81]:
new_df2.to_csv(index=False)

'State,Open,Closed,Pending,Solved\r\nAlabama,4,8,5,9\r\nArizona,2,6,4,8\r\nArkansas,0,1,0,5\r\nCalifornia,47,72,14,87\r\nColorado,12,23,10,35\r\nConnecticut,2,3,1,6\r\nDelaware,3,2,1,6\r\nDistrict Of Columbia,1,5,1,9\r\nDistrict of Columbia,0,0,0,1\r\nFlorida,35,100,4,101\r\nGeorgia,35,82,45,126\r\nIllinois,23,57,6,78\r\nIndiana,8,15,1,35\r\nIowa,0,0,0,1\r\nKansas,0,1,1,0\r\nKentucky,0,1,3,3\r\nLouisiana,0,5,1,7\r\nMaine,2,1,0,2\r\nMaryland,13,24,2,39\r\nMassachusetts,10,24,1,26\r\nMichigan,18,45,5,47\r\nMinnesota,2,9,2,20\r\nMississippi,9,8,7,15\r\nMissouri,1,2,0,1\r\nMontana,0,1,0,0\r\nNevada,0,1,0,0\r\nNew Hampshire,3,4,1,4\r\nNew Jersey,17,23,2,33\r\nNew Mexico,3,5,1,6\r\nNew York,0,2,0,4\r\nNorth Carolina,0,2,0,1\r\nOhio,0,2,0,1\r\nOregon,10,9,3,27\r\nPennsylvania,14,55,6,55\r\nRhode Island,0,1,0,0\r\nSouth Carolina,2,7,1,8\r\nTennessee,33,39,14,57\r\nTexas,18,20,4,29\r\nUtah,6,7,0,9\r\nVermont,1,0,0,2\r\nVirginia,8,21,3,28\r\nWashington,18,35,5,40\r\nWest Virginia,3,6,0,2\r\n'

In [82]:
new_df2.to_csv("Output.csv",index=False)